spring:
  jpa:
    properties:
      hibernate:
        format_sql : true
        highlight_sql : true
        use_sql_comments: true
#    hibernate:
#      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
#server:
#  port: 8181
